import { describe, it, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { access, mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { buildCanonicalMarkdown, writeCanonical } from '../../src/core/canonical.js';
import type { Rule } from '../../src/bridges/types.js';

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function makeRule(overrides: Partial<Rule> = {}): Rule {
  return {
    id: 'test-rule',
    scope: 'conventions',
    severity: 'error',
    content: 'Always use named exports.',
    enabled: true,
    ...overrides,
  };
}

describe('canonical writer', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await mkdtemp(join(tmpdir(), 'devw-canonical-'));
  });

  afterEach(async () => {
    await rm(tmpDir, { recursive: true, force: true });
  });

  describe('buildCanonicalMarkdown', () => {
    it('produces deterministic markdown without frontmatter', () => {
      const rules = [
        makeRule({ id: 'named-exports', content: 'Always use named exports.' }),
        makeRule({ id: 'explicit-return', content: 'Declare return types.\nNever use implicit any.' }),
      ];

      const outputA = buildCanonicalMarkdown('conventions', rules);
      const outputB = buildCanonicalMarkdown('conventions', rules);

      assert.equal(outputA, outputB);
      assert.ok(outputA.startsWith('<!-- Generated by dev-workflows. Do not edit manually. -->'));
      assert.ok(outputA.includes('# Conventions'));
      assert.ok(outputA.includes('- Always use named exports.'));
      assert.ok(outputA.includes('- Declare return types.'));
      assert.ok(outputA.includes('  Never use implicit any.'));
      assert.ok(!outputA.includes('  \n'));
      assert.ok(!outputA.startsWith('---'));
      assert.ok(!outputA.includes('paths:'));
      assert.ok(!outputA.includes('globs:'));
    });
  });

  describe('writeCanonical', () => {
    it('writes canonical files and removes stale dwf files only', async () => {
      const canonicalDir = join(tmpDir, '.agents', 'rules', 'devw');
      await mkdir(canonicalDir, { recursive: true });
      await writeFile(join(canonicalDir, 'dwf-old-scope.md'), 'stale', 'utf-8');
      await writeFile(join(canonicalDir, 'my-custom-notes.md'), 'keep me', 'utf-8');

      const rules = [
        makeRule({ id: 'named-exports', scope: 'conventions' }),
        makeRule({ id: 'no-eval', scope: 'security', content: 'Never use eval().' }),
        makeRule({ id: 'info-rule', scope: 'architecture', severity: 'info', content: 'Informational only.' }),
      ];

      const written = await writeCanonical(tmpDir, rules);

      assert.deepEqual(written, [
        '.agents/rules/devw/dwf-conventions.md',
        '.agents/rules/devw/dwf-security.md',
      ]);

      assert.equal(await fileExists(join(canonicalDir, 'dwf-conventions.md')), true);
      assert.equal(await fileExists(join(canonicalDir, 'dwf-security.md')), true);
      assert.equal(await fileExists(join(canonicalDir, 'dwf-old-scope.md')), false);
      assert.equal(await fileExists(join(canonicalDir, 'my-custom-notes.md')), true);

      const conventions = await readFile(join(canonicalDir, 'dwf-conventions.md'), 'utf-8');
      assert.ok(conventions.includes('# Conventions'));
      assert.ok(!conventions.startsWith('---'));
    });
  });
});
