import { mkdir, writeFile } from 'node:fs/promises';
import { basename, join } from 'node:path';
import type { Rule } from '../bridges/types.js';
import { filterRules, formatScopeHeading, groupByScope } from './helpers.js';
import { cleanStaleFiles, scopeToFilename } from './scope-filename.js';

const GENERATED_COMMENT = '<!-- Generated by dev-workflows. Do not edit manually. -->';
const CANONICAL_DIR_PARTS = ['.agents', 'rules', 'devw'] as const;
const CANONICAL_PREFIX = 'dwf-';
const CANONICAL_EXTENSION = '.md';

export function buildCanonicalMarkdown(scope: string, rules: Rule[]): string {
  const lines: string[] = [GENERATED_COMMENT, `# ${formatScopeHeading(scope)}`, ''];

  for (const rule of rules) {
    const contentLines = rule.content.split('\n');
    const first = contentLines[0];
    if (first !== undefined) {
      lines.push(`- ${first}`);
    }

    for (let i = 1; i < contentLines.length; i++) {
      const line = contentLines[i];
      if (line !== undefined) {
        lines.push(line.length > 0 ? `  ${line}` : '');
      }
    }
  }

  lines.push('');
  return lines.join('\n');
}

export function buildCanonicalOutputs(rules: Rule[]): Map<string, string> {
  const output = new Map<string, string>();
  const filtered = filterRules(rules);
  const grouped = groupByScope(filtered);

  for (const [scope, scopeRules] of grouped) {
    const filename = scopeToFilename(scope, CANONICAL_PREFIX, CANONICAL_EXTENSION);
    const relativePath = join(...CANONICAL_DIR_PARTS, filename);
    output.set(relativePath, buildCanonicalMarkdown(scope, scopeRules));
  }

  return output;
}

export async function writeCanonical(cwd: string, rulesOrOutputs: Rule[] | Map<string, string>): Promise<string[]> {
  const canonicalDir = join(cwd, ...CANONICAL_DIR_PARTS);
  await mkdir(canonicalDir, { recursive: true });

  const outputs = rulesOrOutputs instanceof Map ? rulesOrOutputs : buildCanonicalOutputs(rulesOrOutputs);
  const writtenFilenames = new Set<string>();

  for (const [relativePath, content] of outputs) {
    const filename = basename(relativePath);
    writtenFilenames.add(filename);
    await writeFile(join(cwd, relativePath), content, 'utf-8');
  }

  await cleanStaleFiles(canonicalDir, CANONICAL_PREFIX, CANONICAL_EXTENSION, writtenFilenames);
  return [...outputs.keys()];
}
