import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { claudeBridge } from '../../src/bridges/claude.js';
import type { Rule, ProjectConfig } from '../../src/bridges/types.js';

function makeRule(overrides: Partial<Rule> = {}): Rule {
  return {
    id: 'test-rule',
    scope: 'architecture',
    severity: 'error',
    content: 'Test content',
    enabled: true,
    ...overrides,
  };
}

const CONFIG: ProjectConfig = {
  version: '0.1',
  project: { name: 'test' },
  tools: ['claude'],
  mode: 'copy',
  blocks: [],
  pulled: [],
  assets: [],
  global: true,
};

describe('claudeBridge', () => {
  it('has correct id', () => {
    assert.equal(claudeBridge.id, 'claude');
  });

  it('has kind directory', () => {
    assert.equal(claudeBridge.kind, 'directory');
  });

  it('has correct output directory config', () => {
    assert.equal(claudeBridge.outputDir, '.claude/rules');
    assert.equal(claudeBridge.filePrefix, 'dwf-');
    assert.equal(claudeBridge.fileExtension, '.md');
  });

  it('generates one file per scope', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Use named exports.' }),
      makeRule({ id: 'rule-b', scope: 'conventions', content: 'Use kebab-case.' }),
    ];

    const output = claudeBridge.compile(rules, CONFIG);

    assert.equal(output.size, 2);
    assert.ok(output.has('.claude/rules/dwf-architecture.md'));
    assert.ok(output.has('.claude/rules/dwf-conventions.md'));
  });

  it('includes generated comment in each file', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Use named exports.' }),
    ];

    const output = claudeBridge.compile(rules, CONFIG);
    const content = output.get('.claude/rules/dwf-architecture.md') ?? '';

    assert.ok(content.includes('<!-- Generated by dev-workflows. Do not edit manually. -->'));
  });

  it('includes scope heading in each file', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Use named exports.' }),
      makeRule({ id: 'rule-b', scope: 'conventions', content: 'Use kebab-case.' }),
    ];

    const output = claudeBridge.compile(rules, CONFIG);

    const archContent = output.get('.claude/rules/dwf-architecture.md') ?? '';
    assert.ok(archContent.includes('# Architecture'));
    assert.ok(archContent.includes('- Use named exports.'));

    const convContent = output.get('.claude/rules/dwf-conventions.md') ?? '';
    assert.ok(convContent.includes('# Conventions'));
    assert.ok(convContent.includes('- Use kebab-case.'));
  });

  it('does not include frontmatter when no metadata paths', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Use named exports.' }),
    ];

    const output = claudeBridge.compile(rules, CONFIG);
    const content = output.get('.claude/rules/dwf-architecture.md') ?? '';

    assert.ok(!content.includes('---'));
    assert.ok(!content.includes('paths:'));
  });

  it('includes paths frontmatter when metadata has paths', () => {
    const rules = [
      makeRule({
        id: 'rule-a',
        scope: 'conventions',
        content: 'Use kebab-case.',
        metadata: { paths: ['src/'] },
      }),
    ];

    const output = claudeBridge.compile(rules, CONFIG);
    const content = output.get('.claude/rules/dwf-conventions.md') ?? '';

    assert.ok(content.includes('---'));
    assert.ok(content.includes('paths:'));
    assert.ok(content.includes('  - "src/"'));
  });

  it('handles scope with colon (custom scope)', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'team:payments', content: 'No raw SQL.' }),
    ];

    const output = claudeBridge.compile(rules, CONFIG);

    assert.ok(output.has('.claude/rules/dwf-team-payments.md'));
    const content = output.get('.claude/rules/dwf-team-payments.md') ?? '';
    assert.ok(content.includes('# team:payments'));
    assert.ok(content.includes('- No raw SQL.'));
  });

  it('filters out info and disabled rules', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Keep this.' }),
      makeRule({ id: 'rule-b', scope: 'architecture', severity: 'info', content: 'Skip info.' }),
      makeRule({ id: 'rule-c', scope: 'architecture', enabled: false, content: 'Skip disabled.' }),
    ];

    const output = claudeBridge.compile(rules, CONFIG);
    const content = output.get('.claude/rules/dwf-architecture.md') ?? '';

    assert.ok(content.includes('Keep this.'));
    assert.ok(!content.includes('Skip info.'));
    assert.ok(!content.includes('Skip disabled.'));
  });

  it('returns empty Map when no rules are enabled', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', enabled: false, content: 'Disabled.' }),
    ];

    const output = claudeBridge.compile(rules, CONFIG);

    assert.equal(output.size, 0);
  });

  it('sorts scopes: built-in first, then custom alphabetically', () => {
    const rules = [
      makeRule({ id: 'rule-z', scope: 'team:payments', content: 'No raw SQL.' }),
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Named exports.' }),
      makeRule({ id: 'rule-b', scope: 'conventions', content: 'Kebab case.' }),
    ];

    const output = claudeBridge.compile(rules, CONFIG);
    const keys = [...output.keys()];

    assert.equal(keys[0], '.claude/rules/dwf-architecture.md');
    assert.equal(keys[1], '.claude/rules/dwf-conventions.md');
    assert.equal(keys[2], '.claude/rules/dwf-team-payments.md');
  });

  it('handles multiple paths in metadata', () => {
    const rules = [
      makeRule({
        id: 'rule-a',
        scope: 'conventions',
        content: 'Use kebab-case.',
        metadata: { paths: ['src/', 'lib/'] },
      }),
    ];

    const output = claudeBridge.compile(rules, CONFIG);
    const content = output.get('.claude/rules/dwf-conventions.md') ?? '';

    assert.ok(content.includes('  - "src/"'));
    assert.ok(content.includes('  - "lib/"'));
  });

  it('ignores empty paths array in metadata', () => {
    const rules = [
      makeRule({
        id: 'rule-a',
        scope: 'architecture',
        content: 'Content.',
        metadata: { paths: [] },
      }),
    ];

    const output = claudeBridge.compile(rules, CONFIG);
    const content = output.get('.claude/rules/dwf-architecture.md') ?? '';

    assert.ok(!content.includes('---'));
    assert.ok(!content.includes('paths:'));
  });
});
