import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { cursorBridge } from '../../src/bridges/cursor.js';
import type { Rule, ProjectConfig } from '../../src/bridges/types.js';

function makeRule(overrides: Partial<Rule> = {}): Rule {
  return {
    id: 'test-rule',
    scope: 'architecture',
    severity: 'error',
    content: 'Test content',
    enabled: true,
    ...overrides,
  };
}

const CONFIG: ProjectConfig = {
  version: '0.1',
  project: { name: 'test' },
  tools: ['cursor'],
  mode: 'copy',
  blocks: [],
  pulled: [],
  assets: [],
  global: true,
};

describe('cursorBridge', () => {
  it('has correct id', () => {
    assert.equal(cursorBridge.id, 'cursor');
  });

  it('has kind directory', () => {
    assert.equal(cursorBridge.kind, 'directory');
  });

  it('has correct output directory config', () => {
    assert.equal(cursorBridge.outputDir, '.cursor/rules');
    assert.equal(cursorBridge.filePrefix, 'dwf-');
    assert.equal(cursorBridge.fileExtension, '.mdc');
  });

  it('generates one file per scope', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Use named exports.' }),
      makeRule({ id: 'rule-b', scope: 'conventions', content: 'Use kebab-case.' }),
    ];

    const output = cursorBridge.compile(rules, CONFIG);

    assert.equal(output.size, 2);
    assert.ok(output.has('.cursor/rules/dwf-architecture.mdc'));
    assert.ok(output.has('.cursor/rules/dwf-conventions.mdc'));
  });

  it('includes generated comment in each file', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Use named exports.' }),
    ];

    const output = cursorBridge.compile(rules, CONFIG);
    const content = output.get('.cursor/rules/dwf-architecture.mdc') ?? '';

    assert.ok(content.includes('<!-- Generated by dev-workflows. Do not edit manually. -->'));
  });

  it('includes default frontmatter with alwaysApply: true when no globs', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Use named exports.' }),
    ];

    const output = cursorBridge.compile(rules, CONFIG);
    const content = output.get('.cursor/rules/dwf-architecture.mdc') ?? '';

    assert.ok(content.includes('---'));
    assert.ok(content.includes('description: Architecture rules generated by dev-workflows'));
    assert.ok(content.includes('alwaysApply: true'));
    assert.ok(content.includes('globs:'));
  });

  it('includes globs frontmatter and alwaysApply: false when globs specified', () => {
    const rules = [
      makeRule({
        id: 'rule-a',
        scope: 'conventions',
        content: 'Use kebab-case.',
        metadata: { globs: ['**/*.ts', '**/*.tsx'] },
      }),
    ];

    const output = cursorBridge.compile(rules, CONFIG);
    const content = output.get('.cursor/rules/dwf-conventions.mdc') ?? '';

    assert.ok(content.includes('globs: ["**/*.ts", "**/*.tsx"]'));
    assert.ok(content.includes('alwaysApply: false'));
  });

  it('includes scope heading in each file', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Use named exports.' }),
    ];

    const output = cursorBridge.compile(rules, CONFIG);
    const content = output.get('.cursor/rules/dwf-architecture.mdc') ?? '';

    assert.ok(content.includes('# Architecture'));
    assert.ok(content.includes('- Use named exports.'));
  });

  it('handles scope with colon (custom scope)', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'team:payments', content: 'No raw SQL.' }),
    ];

    const output = cursorBridge.compile(rules, CONFIG);

    assert.ok(output.has('.cursor/rules/dwf-team-payments.mdc'));
    const content = output.get('.cursor/rules/dwf-team-payments.mdc') ?? '';
    assert.ok(content.includes('# team:payments'));
    assert.ok(content.includes('- No raw SQL.'));
  });

  it('filters out info and disabled rules', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Keep this.' }),
      makeRule({ id: 'rule-b', scope: 'architecture', severity: 'info', content: 'Skip info.' }),
      makeRule({ id: 'rule-c', scope: 'architecture', enabled: false, content: 'Skip disabled.' }),
    ];

    const output = cursorBridge.compile(rules, CONFIG);
    const content = output.get('.cursor/rules/dwf-architecture.mdc') ?? '';

    assert.ok(content.includes('Keep this.'));
    assert.ok(!content.includes('Skip info.'));
    assert.ok(!content.includes('Skip disabled.'));
  });

  it('returns empty Map when no rules are enabled', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', enabled: false, content: 'Disabled.' }),
    ];

    const output = cursorBridge.compile(rules, CONFIG);

    assert.equal(output.size, 0);
  });

  it('sorts scopes: built-in first, then custom alphabetically', () => {
    const rules = [
      makeRule({ id: 'rule-z', scope: 'team:payments', content: 'No raw SQL.' }),
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Named exports.' }),
      makeRule({ id: 'rule-b', scope: 'conventions', content: 'Kebab case.' }),
    ];

    const output = cursorBridge.compile(rules, CONFIG);
    const keys = [...output.keys()];

    assert.equal(keys[0], '.cursor/rules/dwf-architecture.mdc');
    assert.equal(keys[1], '.cursor/rules/dwf-conventions.mdc');
    assert.equal(keys[2], '.cursor/rules/dwf-team-payments.mdc');
  });

  it('generates correct description for custom scopes', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'team:payments', content: 'No raw SQL.' }),
    ];

    const output = cursorBridge.compile(rules, CONFIG);
    const content = output.get('.cursor/rules/dwf-team-payments.mdc') ?? '';

    assert.ok(content.includes('description: team:payments rules generated by dev-workflows'));
  });

  it('ignores empty globs array in metadata', () => {
    const rules = [
      makeRule({
        id: 'rule-a',
        scope: 'architecture',
        content: 'Content.',
        metadata: { globs: [] },
      }),
    ];

    const output = cursorBridge.compile(rules, CONFIG);
    const content = output.get('.cursor/rules/dwf-architecture.mdc') ?? '';

    assert.ok(content.includes('alwaysApply: true'));
  });
});
