import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { windsurfBridge } from '../../src/bridges/windsurf.js';
import type { Rule, ProjectConfig } from '../../src/bridges/types.js';

function makeRule(overrides: Partial<Rule> = {}): Rule {
  return {
    id: 'test-rule',
    scope: 'architecture',
    severity: 'error',
    content: 'Test content',
    enabled: true,
    ...overrides,
  };
}

const CONFIG: ProjectConfig = {
  version: '0.1',
  project: { name: 'test' },
  tools: ['windsurf'],
  mode: 'copy',
  blocks: [],
  pulled: [],
};

describe('windsurfBridge', () => {
  it('has correct id', () => {
    assert.equal(windsurfBridge.id, 'windsurf');
  });

  it('has correct output path', () => {
    assert.deepEqual(windsurfBridge.outputPaths, ['.windsurf/rules/devworkflows.md']);
  });

  it('does not use markers', () => {
    assert.equal(windsurfBridge.usesMarkers, false);
  });

  it('generates correct markdown output', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Use named exports.' }),
      makeRule({ id: 'rule-b', scope: 'conventions', content: 'Use kebab-case.' }),
    ];

    const output = windsurfBridge.compile(rules, CONFIG);
    const content = output.get('.windsurf/rules/devworkflows.md');

    assert.ok(content);
    assert.ok(content.includes('<!-- Generated by dev-workflows. Do not edit manually. -->'));
    assert.ok(content.includes('# Project Rules'));
    assert.ok(content.includes('## Architecture'));
    assert.ok(content.includes('- Use named exports.'));
    assert.ok(content.includes('## Conventions'));
    assert.ok(content.includes('- Use kebab-case.'));
  });

  it('sorts scopes: built-in first, then custom alphabetically', () => {
    const rules = [
      makeRule({ id: 'rule-z', scope: 'team:payments', content: 'No raw SQL.' }),
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Named exports.' }),
      makeRule({ id: 'rule-c', scope: 'agent:reviewer', content: 'Review carefully.' }),
      makeRule({ id: 'rule-b', scope: 'conventions', content: 'Kebab case.' }),
    ];

    const output = windsurfBridge.compile(rules, CONFIG);
    const content = output.get('.windsurf/rules/devworkflows.md') ?? '';

    const archIndex = content.indexOf('## Architecture');
    const convIndex = content.indexOf('## Conventions');
    const agentIndex = content.indexOf('## agent:reviewer');
    const teamIndex = content.indexOf('## team:payments');

    assert.ok(archIndex < convIndex, 'Architecture should come before Conventions');
    assert.ok(convIndex < agentIndex, 'Conventions should come before agent:reviewer');
    assert.ok(agentIndex < teamIndex, 'agent:reviewer should come before team:payments');
  });

  it('renders custom scopes without capitalization', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'team:payments', content: 'No raw SQL.' }),
    ];

    const output = windsurfBridge.compile(rules, CONFIG);
    const content = output.get('.windsurf/rules/devworkflows.md') ?? '';

    assert.ok(content.includes('## team:payments'));
    assert.ok(!content.includes('## Team:payments'));
  });

  it('filters out info and disabled rules', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Keep this.' }),
      makeRule({ id: 'rule-b', scope: 'architecture', severity: 'info', content: 'Skip info.' }),
      makeRule({ id: 'rule-c', scope: 'architecture', enabled: false, content: 'Skip disabled.' }),
    ];

    const output = windsurfBridge.compile(rules, CONFIG);
    const content = output.get('.windsurf/rules/devworkflows.md') ?? '';

    assert.ok(content.includes('Keep this.'));
    assert.ok(!content.includes('Skip info.'));
    assert.ok(!content.includes('Skip disabled.'));
  });
});
