import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { windsurfBridge } from '../../src/bridges/windsurf.js';
import type { Rule, ProjectConfig } from '../../src/bridges/types.js';

function makeRule(overrides: Partial<Rule> = {}): Rule {
  return {
    id: 'test-rule',
    scope: 'architecture',
    severity: 'error',
    content: 'Test content',
    enabled: true,
    ...overrides,
  };
}

const CONFIG: ProjectConfig = {
  version: '0.1',
  project: { name: 'test' },
  tools: ['windsurf'],
  mode: 'copy',
  blocks: [],
  pulled: [],
  assets: [],
  global: true,
};

describe('windsurfBridge', () => {
  it('has correct id', () => {
    assert.equal(windsurfBridge.id, 'windsurf');
  });

  it('has kind directory', () => {
    assert.equal(windsurfBridge.kind, 'directory');
  });

  it('has correct output directory config', () => {
    assert.equal(windsurfBridge.outputDir, '.windsurf/rules');
    assert.equal(windsurfBridge.filePrefix, 'dwf-');
    assert.equal(windsurfBridge.fileExtension, '.md');
  });

  it('generates one file per scope', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Use named exports.' }),
      makeRule({ id: 'rule-b', scope: 'conventions', content: 'Use kebab-case.' }),
    ];

    const output = windsurfBridge.compile(rules, CONFIG);

    assert.equal(output.size, 2);
    assert.ok(output.has('.windsurf/rules/dwf-architecture.md'));
    assert.ok(output.has('.windsurf/rules/dwf-conventions.md'));
  });

  it('includes generated comment in each file', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Use named exports.' }),
    ];

    const output = windsurfBridge.compile(rules, CONFIG);
    const content = output.get('.windsurf/rules/dwf-architecture.md') ?? '';

    assert.ok(content.includes('<!-- Generated by dev-workflows. Do not edit manually. -->'));
  });

  it('includes default frontmatter with trigger: always', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Use named exports.' }),
    ];

    const output = windsurfBridge.compile(rules, CONFIG);
    const content = output.get('.windsurf/rules/dwf-architecture.md') ?? '';

    assert.ok(content.includes('---'));
    assert.ok(content.includes('trigger: always'));
  });

  it('uses metadata trigger when specified', () => {
    const rules = [
      makeRule({
        id: 'rule-a',
        scope: 'conventions',
        content: 'Use kebab-case.',
        metadata: { trigger: 'manual' },
      }),
    ];

    const output = windsurfBridge.compile(rules, CONFIG);
    const content = output.get('.windsurf/rules/dwf-conventions.md') ?? '';

    assert.ok(content.includes('trigger: manual'));
  });

  it('includes globs when trigger is glob and globs are provided', () => {
    const rules = [
      makeRule({
        id: 'rule-a',
        scope: 'conventions',
        content: 'Use kebab-case.',
        metadata: { trigger: 'glob', globs: ['**/*.ts', '**/*.tsx'] },
      }),
    ];

    const output = windsurfBridge.compile(rules, CONFIG);
    const content = output.get('.windsurf/rules/dwf-conventions.md') ?? '';

    assert.ok(content.includes('trigger: glob'));
    assert.ok(content.includes('globs: ["**/*.ts", "**/*.tsx"]'));
  });

  it('does not include globs when trigger is always even if globs present', () => {
    const rules = [
      makeRule({
        id: 'rule-a',
        scope: 'conventions',
        content: 'Use kebab-case.',
        metadata: { trigger: 'always', globs: ['**/*.ts'] },
      }),
    ];

    const output = windsurfBridge.compile(rules, CONFIG);
    const content = output.get('.windsurf/rules/dwf-conventions.md') ?? '';

    assert.ok(content.includes('trigger: always'));
    assert.ok(!content.includes('globs:'));
  });

  it('includes scope heading in each file', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Use named exports.' }),
    ];

    const output = windsurfBridge.compile(rules, CONFIG);
    const content = output.get('.windsurf/rules/dwf-architecture.md') ?? '';

    assert.ok(content.includes('# Architecture'));
    assert.ok(content.includes('- Use named exports.'));
  });

  it('handles scope with colon (custom scope)', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'team:payments', content: 'No raw SQL.' }),
    ];

    const output = windsurfBridge.compile(rules, CONFIG);

    assert.ok(output.has('.windsurf/rules/dwf-team-payments.md'));
    const content = output.get('.windsurf/rules/dwf-team-payments.md') ?? '';
    assert.ok(content.includes('# team:payments'));
    assert.ok(content.includes('- No raw SQL.'));
  });

  it('sorts scopes: built-in first, then custom alphabetically', () => {
    const rules = [
      makeRule({ id: 'rule-z', scope: 'team:payments', content: 'No raw SQL.' }),
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Named exports.' }),
      makeRule({ id: 'rule-c', scope: 'agent:reviewer', content: 'Review carefully.' }),
      makeRule({ id: 'rule-b', scope: 'conventions', content: 'Kebab case.' }),
    ];

    const output = windsurfBridge.compile(rules, CONFIG);
    const keys = [...output.keys()];

    assert.equal(keys[0], '.windsurf/rules/dwf-architecture.md');
    assert.equal(keys[1], '.windsurf/rules/dwf-conventions.md');
    assert.equal(keys[2], '.windsurf/rules/dwf-agent-reviewer.md');
    assert.equal(keys[3], '.windsurf/rules/dwf-team-payments.md');
  });

  it('filters out info and disabled rules', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', content: 'Keep this.' }),
      makeRule({ id: 'rule-b', scope: 'architecture', severity: 'info', content: 'Skip info.' }),
      makeRule({ id: 'rule-c', scope: 'architecture', enabled: false, content: 'Skip disabled.' }),
    ];

    const output = windsurfBridge.compile(rules, CONFIG);
    const content = output.get('.windsurf/rules/dwf-architecture.md') ?? '';

    assert.ok(content.includes('Keep this.'));
    assert.ok(!content.includes('Skip info.'));
    assert.ok(!content.includes('Skip disabled.'));
  });

  it('returns empty Map when no rules are enabled', () => {
    const rules = [
      makeRule({ id: 'rule-a', scope: 'architecture', enabled: false, content: 'Disabled.' }),
    ];

    const output = windsurfBridge.compile(rules, CONFIG);

    assert.equal(output.size, 0);
  });
});
