// ── Dialog system ──
const DIALOG_CONTENT = {
  source: {
    icon: { bg: 'linear-gradient(135deg, var(--accent-dim), var(--accent))', text: '{}' },
    filename: '.dwf/rules/conventions.yml',
    code: `<span class="hl-key">scope:</span> <span class="hl-val">conventions</span>

<span class="hl-key">rules:</span>
  - <span class="hl-key">id:</span> named-exports
    <span class="hl-key">severity:</span> <span class="hl-val">error</span>
    <span class="hl-key">content:</span> |
      Always use named exports.
      Never use default exports.
      This applies to all files.

  - <span class="hl-key">id:</span> feature-structure
    <span class="hl-key">severity:</span> <span class="hl-val">error</span>
    <span class="hl-key">content:</span> |
      Organize code by feature, not by type.
      Each feature has its own components,
      hooks, utils, and types.

  - <span class="hl-key">id:</span> no-any
    <span class="hl-key">severity:</span> <span class="hl-val">error</span>
    <span class="hl-key">content:</span> |
      Never use \`any\` in TypeScript.
      Use \`unknown\` and narrow with
      type guards.`
  },
  claude: {
    icon: { bg: 'linear-gradient(135deg, #D97757, #E8956A)', text: '\u2726' },
    filename: 'CLAUDE.md',
    code: `<span class="hl-comment">&lt;!-- Generated by dev-workflows --&gt;</span>
<span class="hl-comment">&lt;!-- Source: .dwf/ | Do not edit manually --&gt;</span>

<span class="hl-heading"># Project Rules</span>

<span class="hl-heading">## Conventions</span>

- Always use named exports.
  Never use default exports.
  This applies to all files.

- Organize code by feature, not by type.
  Each feature has its own components,
  hooks, utils, and types.

- Never use \`any\` in TypeScript.
  Use \`unknown\` and narrow with
  type guards.`
  },
  cursor: {
    icon: { bg: 'linear-gradient(135deg, #8B5CF6, #A78BFA)', text: '\u2318' },
    filename: '.cursor/rules/devworkflows.mdc',
    code: `<span class="hl-comment">---</span>
<span class="hl-key">description:</span> Project rules by dev-workflows
<span class="hl-key">globs:</span>
<span class="hl-key">alwaysApply:</span> <span class="hl-val">true</span>
<span class="hl-comment">---</span>

<span class="hl-comment">&lt;!-- Generated by dev-workflows --&gt;</span>

<span class="hl-heading">## Conventions</span>

- Always use named exports.
  Never use default exports.
  This applies to all files.

- Organize code by feature, not by type.
  Each feature has its own components,
  hooks, utils, and types.

- Never use \`any\` in TypeScript.
  Use \`unknown\` and narrow with
  type guards.`
  },
  gemini: {
    icon: { bg: 'linear-gradient(135deg, #3B82F6, #60A5FA)', text: '\u2726' },
    filename: 'GEMINI.md',
    code: `<span class="hl-comment">&lt;!-- Generated by dev-workflows --&gt;</span>
<span class="hl-comment">&lt;!-- Source: .dwf/ | Do not edit manually --&gt;</span>

<span class="hl-heading"># Project Rules</span>

<span class="hl-heading">## Conventions</span>

- Always use named exports.
  Never use default exports.
  This applies to all files.

- Organize code by feature, not by type.
  Each feature has its own components,
  hooks, utils, and types.

- Never use \`any\` in TypeScript.
  Use \`unknown\` and narrow with
  type guards.`
  }
};

function openDialog(key) {
  const d = DIALOG_CONTENT[key];
  if (!d) return;
  const overlay = document.getElementById('cfDialogOverlay');
  const icon = document.getElementById('cfDialogIcon');
  const filename = document.getElementById('cfDialogFilename');
  const code = document.getElementById('cfDialogCode');

  icon.style.background = d.icon.bg;
  icon.style.color = 'white';
  icon.style.fontSize = '12px';
  icon.textContent = d.icon.text;
  filename.textContent = d.filename;
  code.innerHTML = d.code;
  overlay.classList.add('open');
  document.body.style.overflow = 'hidden';
}

function closeDialog(e) {
  if (e && e.target !== e.currentTarget && !e.target.classList.contains('cf-dialog-close')) return;
  const overlay = document.getElementById('cfDialogOverlay');
  overlay.classList.remove('open');
  document.body.style.overflow = '';
}

document.addEventListener('keydown', (e) => {
  if (e.key === 'Escape') closeDialog();
});
