// ── Playground: Tab switching ──
let currentTab = 'claude';
function switchTab(btn) {
  document.querySelectorAll('.pg-tab').forEach(t => t.classList.remove('active'));
  btn.classList.add('active');
  currentTab = btn.dataset.target;
  renderOutput();
}

// ── Playground: Compile ──
let compiledRules = null;

function parseYAML(text) {
  // Simple YAML parser for our rule format
  const rules = [];
  const blocks = text.split(/(?=  - id:)/);
  for (const block of blocks) {
    const idMatch = block.match(/id:\s*(.+)/);
    const severityMatch = block.match(/severity:\s*(.+)/);
    const contentMatch = block.match(/content:\s*\|\s*\n([\s\S]*?)(?=\n  - id:|\n\S|$)/);

    if (idMatch && contentMatch) {
      const content = contentMatch[1]
        .split('\n')
        .map(l => l.replace(/^\s{6}/, '').trim())
        .filter(l => l)
        .join('\n      ');
      rules.push({
        id: idMatch[1].trim(),
        severity: (severityMatch ? severityMatch[1].trim() : 'error'),
        content: contentMatch[1].split('\n').map(l => l.replace(/^\s{6}/, '').trim()).filter(l => l).join(' ')
      });
    }
  }
  return rules;
}

function compileRules() {
  const btn = document.getElementById('compileBtn');
  const overlay = document.getElementById('compilingOverlay');
  const source = document.getElementById('sourceEditor').value;

  btn.classList.add('compiling');
  btn.innerHTML = '<div class="compile-spinner" style="width:12px;height:12px;border-width:1.5px;"></div> Compiling...';
  overlay.classList.add('active');

  setTimeout(() => {
    compiledRules = parseYAML(source);
    overlay.classList.remove('active');
    btn.classList.remove('compiling');
    btn.innerHTML = '<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="20 6 9 17 4 12"/></svg> Done!';

    renderOutput();

    setTimeout(() => {
      btn.innerHTML = '<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polygon points="5 3 19 12 5 21 5 3"/></svg> Compile';
    }, 1800);
  }, 600);
}

function renderOutput() {
  const placeholder = document.getElementById('outputPlaceholder');
  const codeEl = document.getElementById('outputCode');

  if (!compiledRules || compiledRules.length === 0) {
    placeholder.style.display = 'flex';
    codeEl.style.display = 'none';
    return;
  }

  placeholder.style.display = 'none';
  codeEl.style.display = 'block';

  const now = new Date().toISOString().replace(/\.\d+Z$/, 'Z');

  if (currentTab === 'claude' || currentTab === 'gemini') {
    const filename = currentTab === 'claude' ? 'CLAUDE.md' : 'GEMINI.md';
    let md = `<span class="comment">&lt;!-- Generated by dev-workflows --&gt;</span>\n`;
    md += `<span class="comment">&lt;!-- Source: .dwf/ | Compiled: ${now} --&gt;</span>\n\n`;
    md += `<span class="heading"># Project Rules</span>\n\n`;
    md += `<span class="heading">## Conventions</span>\n\n`;
    for (const r of compiledRules) {
      if (r.severity !== 'info') {
        md += `- ${escapeHtml(r.content)}\n\n`;
      }
    }
    codeEl.innerHTML = md;
  } else if (currentTab === 'cursor') {
    let mdc = `<span class="comment">---</span>\n`;
    mdc += `<span class="key">description:</span> Project rules generated by dev-workflows\n`;
    mdc += `<span class="key">globs:</span>\n`;
    mdc += `<span class="key">alwaysApply:</span> <span class="accent-text">true</span>\n`;
    mdc += `<span class="comment">---</span>\n\n`;
    mdc += `<span class="comment">&lt;!-- Generated by dev-workflows --&gt;</span>\n\n`;
    mdc += `<span class="heading">## Conventions</span>\n\n`;
    for (const r of compiledRules) {
      if (r.severity !== 'info') {
        mdc += `- ${escapeHtml(r.content)}\n\n`;
      }
    }
    codeEl.innerHTML = mdc;
  }
}

function escapeHtml(str) {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
