import type { DirectoryBridge, Rule, ProjectConfig, ScopeMetadata } from './types.js';
import { filterRules, groupByScope, formatScopeHeading } from '../core/helpers.js';
import { scopeToFilename } from '../core/scope-filename.js';

const GENERATED_COMMENT = '<!-- Generated by dev-workflows. Do not edit manually. -->';

function buildFrontmatter(metadata?: ScopeMetadata): string {
  if (!metadata?.paths || metadata.paths.length === 0) {
    return '';
  }

  const lines: string[] = [
    '---',
    'paths:',
  ];
  for (const p of metadata.paths) {
    lines.push(`  - "${p}"`);
  }
  lines.push('---');

  return lines.join('\n');
}

function buildScopeMarkdown(scope: string, rules: Rule[]): string {
  const lines: string[] = [];

  // Get metadata from the first rule in the scope (all rules in a scope share metadata)
  const metadata = rules[0]?.metadata;
  const frontmatter = buildFrontmatter(metadata);

  if (frontmatter) {
    lines.push(frontmatter);
  }

  lines.push(GENERATED_COMMENT);
  lines.push(`# ${formatScopeHeading(scope)}`);
  lines.push('');

  for (const rule of rules) {
    const contentLines = rule.content.split('\n');
    const first = contentLines[0];
    if (first !== undefined) {
      lines.push(`- ${first}`);
    }
    for (let i = 1; i < contentLines.length; i++) {
      const line = contentLines[i];
      if (line !== undefined) {
        lines.push(`  ${line}`);
      }
    }
  }

  lines.push('');
  return lines.join('\n');
}

export const claudeBridge: DirectoryBridge = {
  id: 'claude',
  kind: 'directory',
  outputDir: '.claude/rules',
  filePrefix: 'dwf-',
  fileExtension: '.md',

  compile(rules: Rule[], _config: ProjectConfig): Map<string, string> {
    const output = new Map<string, string>();

    const filtered = filterRules(rules);
    const grouped = groupByScope(filtered);

    for (const [scope, scopeRules] of grouped) {
      const filename = scopeToFilename(scope, 'dwf-', '.md');
      const key = `.claude/rules/${filename}`;
      output.set(key, buildScopeMarkdown(scope, scopeRules));
    }

    return output;
  },
};
