import type { Bridge, Rule, ProjectConfig } from './types.js';
import { filterRules, groupByScope, capitalize } from '../core/helpers.js';

const FRONTMATTER = `---
description: Project rules generated by dev-workflows
globs:
alwaysApply: true
---`;

function buildMdc(rules: Rule[]): string {
  const lines: string[] = [
    FRONTMATTER,
    '',
    '<!-- Generated by dev-workflows. Do not edit manually. -->',
  ];

  const filtered = filterRules(rules);
  const grouped = groupByScope(filtered);

  for (const [scope, scopeRules] of grouped) {
    lines.push('', `## ${capitalize(scope)}`);
    for (const rule of scopeRules) {
      const contentLines = rule.content.split('\n');
      const first = contentLines[0];
      if (first !== undefined) {
        lines.push('', `- ${first}`);
      }
      for (let i = 1; i < contentLines.length; i++) {
        const line = contentLines[i];
        if (line !== undefined) {
          lines.push(`  ${line}`);
        }
      }
    }
  }

  lines.push('');
  return lines.join('\n');
}

export const cursorBridge: Bridge = {
  id: 'cursor',
  outputPaths: ['.cursor/rules/devworkflows.mdc'],

  compile(rules: Rule[], _config: ProjectConfig): Map<string, string> {
    const output = new Map<string, string>();
    output.set('.cursor/rules/devworkflows.mdc', buildMdc(rules));
    return output;
  },
};
