import type { DirectoryBridge, Rule, ProjectConfig, ScopeMetadata } from './types.js';
import { filterRules, groupByScope, formatScopeHeading } from '../core/helpers.js';
import { scopeToFilename } from '../core/scope-filename.js';

const GENERATED_COMMENT = '<!-- Generated by dev-workflows. Do not edit manually. -->';

function buildFrontmatter(scope: string, metadata?: ScopeMetadata): string {
  const hasGlobs = metadata?.globs && metadata.globs.length > 0;
  const description = `${formatScopeHeading(scope)} rules generated by dev-workflows`;

  const lines: string[] = ['---'];
  lines.push(`description: ${description}`);

  if (hasGlobs && metadata?.globs) {
    const globsStr = metadata.globs.map((g) => `"${g}"`).join(', ');
    lines.push(`globs: [${globsStr}]`);
    lines.push('alwaysApply: false');
  } else {
    lines.push('globs:');
    lines.push('alwaysApply: true');
  }

  lines.push('---');
  return lines.join('\n');
}

function buildScopeMdc(scope: string, rules: Rule[]): string {
  const lines: string[] = [];

  const metadata = rules[0]?.metadata;
  lines.push(buildFrontmatter(scope, metadata));
  lines.push(GENERATED_COMMENT);
  lines.push(`# ${formatScopeHeading(scope)}`);
  lines.push('');

  for (const rule of rules) {
    const contentLines = rule.content.split('\n');
    const first = contentLines[0];
    if (first !== undefined) {
      lines.push(`- ${first}`);
    }
    for (let i = 1; i < contentLines.length; i++) {
      const line = contentLines[i];
      if (line !== undefined) {
        lines.push(`  ${line}`);
      }
    }
  }

  lines.push('');
  return lines.join('\n');
}

export const cursorBridge: DirectoryBridge = {
  id: 'cursor',
  kind: 'directory',
  outputDir: '.cursor/rules',
  filePrefix: 'dwf-',
  fileExtension: '.mdc',

  compile(rules: Rule[], _config: ProjectConfig): Map<string, string> {
    const output = new Map<string, string>();

    const filtered = filterRules(rules);
    const grouped = groupByScope(filtered);

    for (const [scope, scopeRules] of grouped) {
      const filename = scopeToFilename(scope, 'dwf-', '.mdc');
      const key = `.cursor/rules/${filename}`;
      output.set(key, buildScopeMdc(scope, scopeRules));
    }

    return output;
  },
};
