import type { Bridge, Rule, ProjectConfig } from './types.js';
import { filterRules, groupByScope, formatScopeHeading } from '../core/helpers.js';

const WINDSURF_CHAR_LIMIT = 6000;

function buildMarkdown(rules: Rule[]): string {
  const lines: string[] = [
    '<!-- Generated by dev-workflows. Do not edit manually. -->',
    '',
    '# Project Rules',
  ];

  const filtered = filterRules(rules);
  const grouped = groupByScope(filtered);

  for (const [scope, scopeRules] of grouped) {
    lines.push('', `## ${formatScopeHeading(scope)}`);
    lines.push('');
    for (const rule of scopeRules) {
      const contentLines = rule.content.split('\n');
      const first = contentLines[0];
      if (first !== undefined) {
        lines.push(`- ${first}`);
      }
      for (let i = 1; i < contentLines.length; i++) {
        const line = contentLines[i];
        if (line !== undefined) {
          lines.push(`  ${line}`);
        }
      }
    }
  }

  lines.push('');
  const content = lines.join('\n');

  if (content.length > WINDSURF_CHAR_LIMIT) {
    console.warn(
      `Warning: Windsurf output is ${String(content.length)} chars (limit: ${String(WINDSURF_CHAR_LIMIT)}). Windsurf may truncate the content.`,
    );
  }

  return content;
}

export const windsurfBridge: Bridge = {
  id: 'windsurf',
  outputPaths: ['.windsurf/rules/devworkflows.md'],
  usesMarkers: false,

  compile(rules: Rule[], _config: ProjectConfig): Map<string, string> {
    const output = new Map<string, string>();
    output.set('.windsurf/rules/devworkflows.md', buildMarkdown(rules));
    return output;
  },
};
