import type { DirectoryBridge, Rule, ProjectConfig, ScopeMetadata } from './types.js';
import { filterRules, groupByScope, formatScopeHeading } from '../core/helpers.js';
import { scopeToFilename } from '../core/scope-filename.js';

const WINDSURF_CHAR_LIMIT = 6000;
const GENERATED_COMMENT = '<!-- Generated by dev-workflows. Do not edit manually. -->';

function buildFrontmatter(metadata?: ScopeMetadata): string {
  const trigger = metadata?.trigger ?? 'always';
  const hasGlobs = metadata?.globs && metadata.globs.length > 0;

  const lines: string[] = ['---'];
  lines.push(`trigger: ${trigger}`);

  if (hasGlobs && trigger === 'glob' && metadata?.globs) {
    const globsStr = metadata.globs.map((g) => `"${g}"`).join(', ');
    lines.push(`globs: [${globsStr}]`);
  }

  lines.push('---');
  return lines.join('\n');
}

function buildScopeMarkdown(scope: string, rules: Rule[]): string {
  const lines: string[] = [];

  const metadata = rules[0]?.metadata;
  lines.push(buildFrontmatter(metadata));
  lines.push(GENERATED_COMMENT);
  lines.push(`# ${formatScopeHeading(scope)}`);
  lines.push('');

  for (const rule of rules) {
    const contentLines = rule.content.split('\n');
    const first = contentLines[0];
    if (first !== undefined) {
      lines.push(`- ${first}`);
    }
    for (let i = 1; i < contentLines.length; i++) {
      const line = contentLines[i];
      if (line !== undefined) {
        lines.push(`  ${line}`);
      }
    }
  }

  lines.push('');
  const content = lines.join('\n');

  if (content.length > WINDSURF_CHAR_LIMIT) {
    console.warn(
      `Warning: Windsurf file for scope "${scope}" is ${String(content.length)} chars (limit: ${String(WINDSURF_CHAR_LIMIT)}). Windsurf may truncate the content.`,
    );
  }

  return content;
}

export const windsurfBridge: DirectoryBridge = {
  id: 'windsurf',
  kind: 'directory',
  outputDir: '.windsurf/rules',
  filePrefix: 'dwf-',
  fileExtension: '.md',

  compile(rules: Rule[], _config: ProjectConfig): Map<string, string> {
    const output = new Map<string, string>();

    const filtered = filterRules(rules);
    const grouped = groupByScope(filtered);

    for (const [scope, scopeRules] of grouped) {
      const filename = scopeToFilename(scope, 'dwf-', '.md');
      const key = `.windsurf/rules/${filename}`;
      output.set(key, buildScopeMarkdown(scope, scopeRules));
    }

    return output;
  },
};
